# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore

    - name: Install SmugMugCore package (MetadataExtractor)
      run: dotnet add package MetadataExtractor --version 2.8.1
    - name: Install SmugMugCore package (ShellExtensions)
      run: dotnet add package Microsoft-WindowsAPICodePack-ShellExtensions --version 1.1.5
    - name: Install SmugMugCore.Net and SmugMugCoreSync package (System.IO.Abstractions)
      run: System.IO.Abstractions --version 19.2.64
    - name: Install SmugMugCoreSync package (JSON Extension)
      run: Microsoft.Extensions.Configuration.Json --version 8.0.0-preview.6.23329.7
      

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
